---
output:
  html_document: default
  pdf_document: default
---
```{r}
library(ggplot2)

data <- read.csv("C:\\Users\\hp\\OneDrive\\Documents\\Semester 2\\Data Prep\\Project\\CTA_-_Ridership_-__L__Station_Entries_-_Monthly_Day-Type_Averages___Totals.csv", header=TRUE)

ggplot(data, aes(x=monthtotal)) + 
  geom_line(aes(y = Weekday_Rides ), color = "darkred",linetype="twodash") + 
  geom_line(aes(y = Saturday_Rides), color="steelblue", linetype="twodash")+
  geom_line(aes(y = Sunday_Holiday_Rides), color="darkgreen", linetype="twodash")+
  ggtitle("Comparing L-Train Rides based on days")+
  xlab("Monthly Rides")+ylab("Rides") +
  scale_color_manual(name = "Days",
                     values = c("darkred", "steelblue", "darkgreen"),
                     labels = c("Weekday", "Saturday", "Sunday/Holiday"))
```

```{r}
data<-read.csv("C:\\Users\\hp\\OneDrive\\Documents\\Semester 2\\Data Prep\\Project\\CTA_-_Ridership_-_Bus_Routes_-_Monthly_Day-Type_Averages___Totals.csv")

ggplot(data, aes(x=monthtotal)) + 
  geom_line(aes(y = Weekday_Rides ), color = "darkred",linetype="twodash") + 
  geom_line(aes(y = Saturday_Rides), color="steelblue", linetype="twodash")+
  geom_line(aes(y = Sunday_Holiday_Rides), color="darkgreen", linetype="twodash")+
  ggtitle("Comparing Bus Rides based on days")+
  xlab("Monthly Rides")+ylab("Rides") +
  scale_color_manual(name = "Days",
                     values = c("darkred", "steelblue", "darkgreen"),
                     labels = c("Weekday", "Saturday", "Sunday/Holiday"))
```

